### PR TITLE
Break apart router into multiple modules

### PR DESCRIPTION
**Pull request by davejlong**
As the project grows, it seems to make sense to break the router up from one giant module handling all of the API requests to a small base router which passes requests off to modules for each area of the Kitto API. I broke up the router based on the current endpoints defined: dashboards, events and widgets. Doing this now while the project is young will be much easier then trying to coordinate breaking the router up later when things are much larger.

The dashboard endpoint handles all requests to open dashboards as well as sending reload events to them.

The event endpoint handles opening a new SSE connection to stream events to a client.

The widget endpoint handles getting data for a specific data source or posting into a data source.

### CODE REVIEW

**Comment by davejlong** [comment]
Not totally sure why there are so many commits between the 2 branches. All of the commits are from the `plugify-authentication` branch. I've noticed this a couple of times already. @Zorbash is there something about how I'm submitting PRs that's doing this or is it how PRs are being merged?

**Comment by davejlong** [comment]
I will bring the test coverage backup before this gets merged.

**Comment by zorbash** [comment]
@davejlong your branch seems to have diverged from master because i rebased and squashed you commits on `plugify-authentication` before merging. I didn't want to post comments for every tiny change in the commit message/title so i decided to quickly do it myself. Nothing to worry about. After resolving #27 it's going to be much easier to cooperate based on a set of git / coding style standards.

**Comment by davejlong** [comment]
Will look at reopening as a different PR in the future without the merge conflicts.

**Pull request closed without merging**
