### PR TITLE
Add empty parentheses to silence Elixir 1.4 warnings

### PR DESCRIPTION
**Pull request by fusillicode**
This PR addresses the issue #89 and aims to solve all the warnings related to the missing empty parentheses that are raised at compilation time.

### CODE REVIEW

**Comment by Zorbash** [comment]
Hello, @fusillicode! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/kittoframework/kitto/pulls/90). Please check our [documentation](https://ebertapp.io/docs) for more information.

**Comment by Zorbash** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 3 possible new issues (including those that may have been commented here).
* 2 fixed issues! 🎉

You can see more details about this review at https://ebertapp.io/github/kittoframework/kitto/pulls/90.

**Comment by Zorbash** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 2 possible new issues (including those that may have been commented here).
* 2 fixed issues! 🎉

You can see more details about this review at https://ebertapp.io/github/kittoframework/kitto/pulls/90.

**Comment by Zorbash** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 1 possible new issue (including those that may have been commented here).
* 2 fixed issues! 🎉

You can see more details about this review at https://ebertapp.io/github/kittoframework/kitto/pulls/90.

**Comment by zorbash** [comment]
Thanks a lot @fusillicode :heart:

**Comment by fusillicode** [comment]
I'm the one who should be thankful to you @Zorbash (and to all Kitto creators and maintainers) 🤗

You're doing an awesome job! Keep on! 👌😎

I hope to be able to contribute to more "important" issues in the future 😄

**Pull request merged**
